import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Profile from "../public/mainphoto.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio-Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.navbar}>
        <div className={styles.logo}>PortFolio</div>

        <div className={styles.Links}>
          <a href="#" className={styles.linkbtns}>
            Home
          </a>
          <a href="#" className={styles.linkbtns}>
            Projects
          </a>
          <a href="#" className={styles.linkbtns}>
            About
          </a>
          <a href="#" className={styles.linkbtns}>
            Contact
          </a>
        </div>

        <div className={styles.bt}>
          <button className={styles.buttons}>Hire Me</button>
        </div>
      </div>

      <main>
        <div className={styles.Mainbox}>
          <div className={styles.TextInfo}>
            <h1 className={styles.heading}>
              Hello, I am <span className={styles.Mainname}>FSDev.</span>
            </h1>
            <h3 className={styles.heading}>Graphic Designer Expert.. </h3>
            <button className={styles.butone}>Get My CV</button>
            <button className={styles.buttwo}>Call Me</button>
          </div>
          <div className={styles.Image}>
            <Image
              src={Profile}
              alt="Picture of the author"
              width={500}
              height={500}
              className={styles.mainphoto}
            />
          </div>
        </div>

        <div className={styles.mainblue}>
          <h1 className={styles.Myskils}>My Skills</h1>
          <h3 className={styles.Myskils}>
            <li>Adobe Photoshop</li>
          </h3>
          <h3 className={styles.Myskils}>
            <li>Adobe Illustrator</li>
          </h3>
          <h3 className={styles.Myskils}>
            <li>Sketch</li>
          </h3>
          <h3 className={styles.Myskils}>
            <li>Adobe InDesign</li>
          </h3>
          <h3 className={styles.Myskils}>
            <li>Adobe XD</li>
          </h3>
        </div>

        <h1 className={styles.Headingin}>Footer Section</h1>

        <div className={styles.footer}>
          <h1>
            For Details or Any editing stuff Please Contact me on call: 009-000
          </h1>
          <h3>Editing & Design</h3>
          <h3>2020 &copy;</h3>
        </div>
      </main>
    </div>
  );
}
